#!/usr/bin/env bash

# Let's get this party started! Installing homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"

# Updating and adding taps
brew update

# A few gems: lunchy is for creating tasks with launchd 
#			  homesick is for dotfile management
#printf "\nInstalling a few ruby gems with brew.\n"
#brew gem lunchy
#brew gem homesick

# My favorite tools
apps=(ack
	  bash-completion
	  brew-gem
	  #coreutils
	  gfortran
	  gnuplot --cairo --latex --pdf --qt --with-x --wx
	  grc
	  htop-osx
	  ssh-copy-id
	  tree
	  vim --override-system-vi
	  wget
	  z
	  zsh)

printf "Installing my favorite tools with brew.\n"
for app in "${apps[*]}"; do
	brew install $app
done

# Clean up after yourself
brew cleanup -s
#rm -rf brew --cache
