# Brewfile

# run this by running 'brew bundle path/to/Brewfile'

# Always update and upgrade installed packages first
update
upgrade

# These are my favorite tools to use from the command line. I love it!!
install ack
install bash
install bash-completion
#install brew-gem
install coreutils
install curl
install exiftool
install findutils
install gcc
install gifsicle
install git
install gnuplot --with-latex --with-x11 --with-cairo --with-pdflib-lite --with-wxmac --with-qt
install grc
install hub
install htop-osx
install poppler
#install ssh-copy-id
install screenfetch
install todo-txt
install tree
install vim
install w3m
install wget
install xz
install z
install zsh

# Using brew-gem to install ruby gems
# gem jekyll

# Clean up after yourself
cleanup -s
